### ISSUE TITLE
6.3.1 doesn't work with the esm module loader

### ISSUE THREAD

**Issue by philipmarnef** [1000ch/gulp-image#141]
Possibly related to #139

When using `esm`, `gulp-image 6.3.1` throws an error on all node versions I tried (14, 16 & 17):

```
[10:33:08] Requiring external module esm
TypeError: Invalid host defined options
    at eval (eval at <anonymous> (/Users/philipmarnef/Sites/xxxxxxxx/node_modules/gulp-cli/lib/shared/require-or-import.js:10:15), <anonymous>:3:1)
    at requireOrImport (/Users/philipmarnef/Sites/xxxxxxxx/node_modules/gulp-cli/lib/shared/require-or-import.js:24:7)
    at execute (/Users/philipmarnef/Sites/xxxxxxxx/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:37:3)
    at Liftoff.handleArguments (/Users/philipmarnef/Sites/xxxxxxxx/node_modules/gulp-cli/index.js:211:24)
    at Liftoff.execute (/Users/philipmarnef/Sites/xxxxxxxx/node_modules/liftoff/index.js:201:12)
    at module.exports (/Users/philipmarnef/Sites/xxxxxxxx/node_modules/flagged-respawn/index.js:51:3)
    at Liftoff.<anonymous> (/Users/philipmarnef/Sites/xxxxxxxx/node_modules/liftoff/index.js:191:5)
    at /Users/philipmarnef/Sites/xxxxxxxx/node_modules/liftoff/index.js:149:9
    at /Users/philipmarnef/Sites/xxxxxxxx/node_modules/v8flags/index.js:162:14
    at /Users/philipmarnef/Sites/xxxxxxxx/node_modules/v8flags/index.js:41:14
```

Downgrading to 6.2.1 solves the issue.

**Comment by ahoran3** [comment]
downgrading to 6.2.1 has a broken dependency: SVGO. 

`svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.`

**Comment by philipmarnef** [comment]
esm is now obsolete, removing it solved the issue
