### ISSUE TITLE
Encountered bug while install in Mac.

### ISSUE THREAD

**Issue by darting** [1000ch/gulp-image#17]
error:

```
> jpeg-recompress-bin@3.0.1 postinstall /Users/abc/work/HTML5GameEngine/node_modules/jpeg-recompress-bin
> node lib/install.js

  ✔ jpeg-recompress pre-build test passed successfully

> jpegoptim-bin@3.0.0 postinstall /Users/abc/work/HTML5GameEngine/node_modules/jpegoptim-bin
> node lib/install.js

  ⚠ The `/Users/abc/work/HTML5GameEngine/node_modules/jpegoptim-bin/vendor/jpegoptim` binary doesn't seem to work correctly
  ⚠ jpegoptim pre-build test failed
  ℹ compiling from source
  ✖ Error: ./configure --prefix="/Users/abc/work/HTML5GameEngine/node_modules/jpegoptim-bin/vendor" --bindir="/Users/abc/work/HTML5GameEngine/node_modules/jpegoptim-bin/vendor" && make install
Command failed: ./configure --prefix="/Users/abc/work/HTML5GameEngine/node_modules/jpegoptim-bin/vendor" --bindir="/Users/abc/work/HTML5GameEngine/node_modules/jpegoptim-bin/vendor"

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)

> mozjpeg@4.1.1 postinstall /Users/abc/work/HTML5GameEngine/node_modules/mozjpeg
> node lib/install.js

  ⚠ The `/Users/abc/work/HTML5GameEngine/node_modules/mozjpeg/vendor/cjpeg` binary doesn't seem to work correctly
  ⚠ mozjpeg pre-build test failed
  ℹ compiling from source
  ✖ Error: autoreconf -fiv && ./configure --disable-shared --prefix="/Users/abc/work/HTML5GameEngine/node_modules/mozjpeg/vendor" --bindir="/Users/abc/work/HTML5GameEngine/node_modules/mozjpeg/vendor" --libdir="/Users/abc/work/HTML5GameEngine/node_modules/mozjpeg/vendor" && make --jobs=8 && make install --jobs=8
Command failed: ./configure --disable-shared --prefix="/Users/abc/work/HTML5GameEngine/node_modules/mozjpeg/vendor" --bindir="/Users/abc/work/HTML5GameEngine/node_modules/mozjpeg/vendor" --libdir="/Users/abc/work/HTML5GameEngine/node_modules/mozjpeg/vendor"
configure: error: installation or configuration problem: assembler cannot create object files.

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
```

OS X (10.11.5 (15F34))
 node v6.2.0

any idea?

thanks.

**Comment by 1000ch** [comment]
Can you install them manually?

```sh
npm install mozjpeg jpegoptim-bin
```

**Comment by darting** [comment]
@1000ch after `brew install libjpeg` then reinstall gulp-image, it is working now.

**Comment by 1000ch** [comment]
Fine.
