### ISSUE TITLE
Error: write EPIPE

### ISSUE THREAD

**Issue by Abhi347** [1000ch/gulp-image#23]
I was using gulp-imagemin before, which worked perfectly, but wanted to give gulp-image a try. But it's failing with a strange error.

```
$ gulp image
[07:07:05] Using gulpfile /Volumes/Dev/Web/Node.js/NoobGuy/gulpfile.js
[07:07:05] Starting 'image'...
[07:07:05] Finished 'image' after 14 ms
Error: write EPIPE
    at exports._errnoException (util.js:907:11)
    at WriteWrap.afterWrite (net.js:785:14)
```

Here's what I have in my gulpfile.js

```
var image = require('gulp-image');
gulp.task('image', function(){
    gulp.src('./public/assets/images/**/*',{'base':'./public/assets/images/'})
        .pipe(image())
        .pipe(gulp.dest('./public/assets/dist/images'));
});
```

I was using the same code with gulp-imagemin which worked properly. Am I doing something wrong?

**Comment by sathyalog** [comment]
Even i am facing the same issue. Looking for some help.

**Comment by tammyhart** [comment]
also getting the same error unless I specify extensions in which case, it only processes `.png`

**Comment by anuraag279** [comment]
+1

**Comment by AlvSovereign** [comment]
I'm getting the same as well:

`events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1026:11)
    at WriteWrap.afterWrite (net.js:799:14)`

**Comment by 1000ch** [comment]
I cannot reproduce this issue, let me isolate the problem (which envs or settings).
Does anyone upload settings and images that reproduce this?

**Comment by baacke** [comment]
I get the same error unless I remove jpg from the glob or set mozjpeg to false. I haven't specified any other settings.

Also, the only other thing worth noting about the 1 jpg I have is that now when it runs it says it Cannot improve upon XX.XX KB.

**Comment by in-in** [comment]
Same error
```shell
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1022:11)
    at WriteWrap.afterWrite (net.js:804:14)
```

During installation there is an error:

```shell
ubuntu@ubuntu-xenial:/home/project$ npm i
  ✔ gifsicle pre-build test passed successfully
  ✔ jpeg-recompress pre-build test passed successfully
  ⚠ The `/home/project/node_modules/jpegoptim-bin/vendor/jpegoptim` binary doesn't seem to work correctly
  ⚠ jpegoptim pre-build test failed
  ℹ compiling from source
  ✖ Error: ./configure --prefix="/home/project/node_modules/jpegoptim-bin/vendor" --bindir="/home/project/node_modules/jpegoptim-bin/vendor" && make install
Command failed: ./configure --prefix="/home/project/node_modules/jpegoptim-bin/vendor" --bindir="/home/project/node_modules/jpegoptim-bin/vendor"

    at ChildProcess.exithandler (child_process.js:211:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  ✔ mozjpeg pre-build test passed successfully
  ✔ optipng pre-build test passed successfully
  ✔ pngquant pre-build test passed successfully
  ✔ zopflipng pre-build test passed successfully
/home/project
```

$ uname -a
`Linux ubuntu-xenial 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
$ node -v && npm -v
```shell
v7.2.0
3.10.9
```

**Comment by CoffiDev** [comment]
I'm having the same issue:

```
[08:44:37] Starting 'image'...
[08:44:37] Finished 'image' after 16 ms
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1026:11)
    at WriteWrap.afterWrite (net.js:799:14)
```

Node: 6.9.1
Npm: 3.10.8

In my gulpfile I have:
```
gulp.task('image', function () {
  gulp.src('assets/*')
    .pipe(image())
    .pipe(gulp.dest('dist/assets'));
});
```

The error during the installation is:

```
 ⚠ The `/Users/alex/h/steed/pabloescobarinfraganti.com/node_modules/jpegoptim-bin/vendor/jpegoptim` binary doesn't seem to work correctly
  ⚠ jpegoptim pre-build test failed
  ℹ compiling from source
  ✖ Error: ./configure --prefix="/Users/alex/h/steed/pabloescobarinfraganti.com/node_modules/jpegoptim-bin/vendor" --bindir="/Users/alex/h/steed/pabloescobarinfraganti.com/node_modules/jpegoptim-bin/vendor" && make install
Command failed: ./configure --prefix="/Users/alex/h/steed/pabloescobarinfraganti.com/node_modules/jpegoptim-bin/vendor" --bindir="/Users/alex/h/steed/pabloescobarinfraganti.com/node_modules/jpegoptim-bin/vendor"

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)

> mozjpeg@4.1.1 postinstall /Users/alex/h/steed/pabloescobarinfraganti.com/node_modules/mozjpeg
> node lib/install.js

  ⚠ The `/Users/alex/h/steed/pabloescobarinfraganti.com/node_modules/mozjpeg/vendor/cjpeg` binary doesn't seem to work correctly
  ⚠ mozjpeg pre-build test failed
  ℹ compiling from source
  ✖ Error: autoreconf -fiv && ./configure --disable-shared --prefix="/Users/alex/h/steed/pabloescobarinfraganti.com/node_modules/mozjpeg/vendor" --bindir="/Users/alex/h/steed/pabloescobarinfraganti.com/node_modules/mozjpeg/vendor" --libdir="/Users/alex/h/steed/pabloescobarinfraganti.com/node_modules/mozjpeg/vendor" && make --jobs=4 && make install --jobs=4
Command failed: ./configure --disable-shared --prefix="/Users/alex/h/steed/pabloescobarinfraganti.com/node_modules/mozjpeg/vendor" --bindir="/Users/alex/h/steed/pabloescobarinfraganti.com/node_modules/mozjpeg/vendor" --libdir="/Users/alex/h/steed/pabloescobarinfraganti.com/node_modules/mozjpeg/vendor"
./configure: line 13758: syntax error near unexpected token `libpng,'
./configure: line 13758: `PKG_CHECK_MODULES(libpng, libpng, HAVE_LIBPNG=1,'

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**Comment by dkouvdis** [comment]
Temp solution, disable those below.
mozjpeg: false
jpegoptim: false

**Comment by kamilczujowski** [comment]
any "final" solution?

**Comment by michaelpumo** [comment]
I'd also like to see a solution to this if possible. Any ideas? JPG optimisation would be great to have.

**Comment by bertalanimre** [comment]
Also waiting for an aswer. This is frustrating.

**Comment by 1000ch** [comment]
Would you try re-installing jpegoptim-bin? https://github.com/1000ch/gulp-image/issues/22#issuecomment-315613709

**Comment by evayde** [comment]
I encountered this issue on Debian Stretch (9), while it was working on Jessie and Wheezy. 
You have to manually update the bin until there's another solution. 

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install jpegoptim
make sure you rename the jpegoptim in your node_modules folder to jpegoptim.bak or something, so you can go back if you want. You can also remove it, of course. 
sudo ln -s /usr/bin/jpegoptim /your/node_modules/jpegoptim-bin/vendor/jpegoptim

**Comment by tomhoad** [comment]
For the record, on MacOS:

`brew install libjpeg`
`npm install --global jpegoptim-bin`
