### ISSUE TITLE
NPM 5.6.0 can't install gulp-image

### ISSUE THREAD

**Issue by econavi** [1000ch/gulp-image#44]
Hi!
I have a problem with the gulp-image.
I can't install that with npm 5.6.0.

```
MacBook-Air:t2 Acrob$ sudo npm i
Password:

> gifsicle@3.0.4 postinstall /Users/Acrob/dev/t2/node_modules/gifsicle
> node lib/install.js

  ⚠ EACCES: permission denied, mkdir '/Users/Acrob/dev/t2/node_modules/gifsicle/vendor'
  ⚠ gifsicle pre-build test failed
  ℹ compiling from source
/Users/Acrob/dev/t2/node_modules/onetime/index.js:15
				throw new Error(fnName + ' can only be called once.');
				^

Error: callback() can only be called once.
    at onetime (/Users/Acrob/dev/t2/node_modules/onetime/index.js:15:11)
    at /Users/Acrob/dev/t2/node_modules/download/index.js:156:5
    at ConcatStream.<anonymous> (/Users/Acrob/dev/t2/node_modules/concat-stream/index.js:36:43)
    at emitNone (events.js:111:20)
    at ConcatStream.emit (events.js:208:7)
    at finishMaybe (/Users/Acrob/dev/t2/node_modules/readable-stream/lib/_stream_writable.js:620:14)
    at endWritable (/Users/Acrob/dev/t2/node_modules/readable-stream/lib/_stream_writable.js:628:3)
    at ConcatStream.Writable.end (/Users/Acrob/dev/t2/node_modules/readable-stream/lib/_stream_writable.js:584:41)
    at DuplexWrapper.onend (/Users/Acrob/dev/t2/node_modules/readable-stream/lib/_stream_readable.js:577:10)
    at Object.onceWrapper (events.js:313:30)
npm WARN t2@1.0.0 No description
npm WARN t2@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gifsicle@3.0.4 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gifsicle@3.0.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Acrob/.npm/_logs/2018-02-22T08_29_04_672Z-debug.log
```

**Comment by 1000ch** [comment]
It seems a problem for installing gifsicle, not a problem for npm.
Would you try install `gifsicle` with `npm install gifsicle` on your MacBook Air?
